### PR TITLE
Build with clang 5.0 by adding -std=c++11

### PR DESCRIPTION
**Pull request by qzmfranklin**
The Bazel BUILD file lacks a few `-std=c++11` flags.

On a Ubuntu 16.04 x86_64 machine with clang5.0.0, the default dialect of C++ is pretty old. We should mandate it to at least c++11.

Some errors I got without using these `-std=c++11` flags are:
```
re2/re2.h:915:5: error: no matching function for call to 'call_once'
    std::call_once(once_, &LazyRE2::Init, this);
```

All tests pass as I tested.

### CODE REVIEW

**Comment by junyer** [comment]
Thank you for the contribution! Alas, setting the language standard like this isn't the right approach. Other users might want C++14 or even C++17, for example, and "mixing" language standards won't end well.

https://stackoverflow.com/q/40260242 suggests a couple of options: passing `--cxxopt` flags to Bazel is the quick and dirty solution; defining a custom toolchain via the `CROSSTOOL` file is the proper solution. https://groups.google.com/d/msg/bazel-discuss/N1qvsGMJoAE/IAAiXI6CAgAJ has another tip for wrangling custom toolchains.

**Comment by junyer** [comment]
P.S. We use Gerrit as per https://github.com/google/re2/wiki/Contribute, not pull requests. :)

**Comment by qzmfranklin** [comment]
Hi @junyer ,

Thanks for the replies! Got it. It makes sense your way.
Also, will keep in mind to use Gerrit next time.
