### ISSUE TITLE
clang: 'private field severity_ is not used' warning

### ISSUE THREAD

**Issue by zeux** [google/re2#117]
I'm using RE2 in a project with -Wall -Werror, and am getting this warning (converted to error):

> In file included from extern/re2/re2/bitstate.cc:24:
> extern/re2/util/logging.h:78:13: error: private field 'severity_' is not used [-Werror,-Wunused-private-field]
>  const int severity_;

on Travis CI Mac build:

https://travis-ci.org/zeux/qgrep/jobs/162551576#L56

It seems to be initialized but not used for anything.

**Comment by zeux** [comment]
Looks like it's a regression from 93583735faf4ca41c1e13ea302f61bc83e49b7bc.
